// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $admin from "./routes/admin.tsx";
import * as $api_sync from "./routes/api/sync.ts";
import * as $api_watch from "./routes/api/watch.ts";
import * as $auth from "./routes/auth.tsx";
import * as $index from "./routes/index.tsx";
import * as $map from "./islands/map.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/admin.tsx": $admin,
    "./routes/api/sync.ts": $api_sync,
    "./routes/api/watch.ts": $api_watch,
    "./routes/auth.tsx": $auth,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/map.tsx": $map,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
